<a href="https://colab.research.google.com/github/EminIsmayilzada/Machine-Learning/blob/main/full_pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!kaggle datasets download -d parisrohan/credit-score-classification

Dataset URL: https://www.kaggle.com/datasets/parisrohan/credit-score-classification
License(s): CC0-1.0
Downloading credit-score-classification.zip to /content
 53% 5.00M/9.51M [00:00<00:00, 43.6MB/s]
100% 9.51M/9.51M [00:00<00:00, 55.6MB/s]

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
!unzip /content/credit-score-classification.zip

Archive:  /content/credit-score-classification.zip
  inflating: test.csv
  inflating: train.csv

In [ ]:
df = pd.read_csv('/content/train.csv')

<ipython-input-4-337b670ff17c>:1: DtypeWarning: Columns (26) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/content/train.csv')

In [ ]:
df.columns

Index(['ID', 'Customer_ID', 'Month', 'Name', 'Age', 'SSN', 'Occupation',
       'Annual_Income', 'Monthly_Inhand_Salary', 'Num_Bank_Accounts',
       'Num_Credit_Card', 'Interest_Rate', 'Num_of_Loan', 'Type_of_Loan',
       'Delay_from_due_date', 'Num_of_Delayed_Payment', 'Changed_Credit_Limit',
       'Num_Credit_Inquiries', 'Credit_Mix', 'Outstanding_Debt',
       'Credit_Utilization_Ratio', 'Credit_History_Age',
       'Payment_of_Min_Amount', 'Total_EMI_per_month',
       'Amount_invested_monthly', 'Payment_Behaviour', 'Monthly_Balance',
       'Credit_Score'],
      dtype='object')

In [ ]:
df.describe()

,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Delay_from_due_date,Num_Credit_Inquiries,Credit_Utilization_Ratio,Total_EMI_per_month
count,84998.000000,100000.000000,100000.00000,100000.000000,100000.000000,98035.000000,100000.000000,100000.000000
mean,4194.170850,17.091280,22.47443,72.466040,21.068780,27.754251,32.285173,1403.118217
std,3183.686167,117.404834,129.05741,466.422621,14.860104,193.177339,5.116875,8306.041270
min,303.645417,-1.000000,0.00000,1.000000,-5.000000,0.000000,20.000000,0.000000
25%,1625.568229,3.000000,4.00000,8.000000,10.000000,3.000000,28.052567,30.306660
50%,3093.745000,6.000000,5.00000,13.000000,18.000000,6.000000,32.305784,69.249473
75%,5957.448333,7.000000,7.00000,20.000000,28.000000,9.000000,36.496663,161.224249
max,15204.633333,1798.000000,1499.00000,5797.000000,67.000000,2597.000000,50.000000,82331.000000

In [ ]:
df['Age']= df['Age'].str.replace('_','').str.replace('-500','50')
df['Annual_Income']= df['Annual_Income'].str.replace('_','')
df['Num_of_Loan']= df['Num_of_Loan'].str.replace('_','')
df['Num_of_Delayed_Payment']=df['Num_of_Delayed_Payment'].str.replace('_','')
df['Changed_Credit_Limit']=df['Changed_Credit_Limit'].str.replace('_','')
df['Outstanding_Debt']=df['Outstanding_Debt'].str.replace('_','')
df['Amount_invested_monthly']=df['Amount_invested_monthly'].str.replace('_','')

In [ ]:
df['Monthly_Balance']=df['Monthly_Balance'].str.replace('_','').str.replace('-','').str.replace('333333333333333333333333333','')

In [ ]:
df['Age']=pd.to_numeric(df['Age'])
df['Annual_Income']=pd.to_numeric(df['Annual_Income'])
df['Num_of_Loan']=pd.to_numeric(df['Num_of_Loan'])
df['Num_of_Delayed_Payment']=pd.to_numeric(df['Num_of_Delayed_Payment'])
df['Changed_Credit_Limit']=pd.to_numeric(df['Changed_Credit_Limit'])
df['Outstanding_Debt']=pd.to_numeric(df['Outstanding_Debt'])
df['Amount_invested_monthly']=pd.to_numeric(df['Amount_invested_monthly'])
df['Monthly_Balance']=pd.to_numeric(df['Monthly_Balance'])

In [ ]:
df['Age']= df['Age'].apply(lambda col: np.where(col>100, np.nan, col))

In [ ]:
df['Before_payment']= df['Delay_from_due_date']

In [ ]:
df['Num_Bank_Accounts']=df['Num_Bank_Accounts'].apply(lambda col: np.where(col>30, np.nan, col))
df['Num_Credit_Card']=df['Num_Credit_Card'].apply(lambda col: np.where(col>20, np.nan, col))
df['Num_of_Loan']=df['Num_of_Loan'].apply(lambda col: np.where(col<0, np.nan, col))
df['Delay_from_due_date']=df['Delay_from_due_date'].apply(lambda col: np.where(col<0, np.nan, col))
df['Before_payment']=df['Before_payment'].apply(lambda col: np.where(col>0, np.nan, col))
df['Before_payment']=df['Before_payment'].apply(lambda col: np.where(col<0, col*-1, col))

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 29 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   ID                        100000 non-null  object
 1   Customer_ID               100000 non-null  object
 2   Month                     100000 non-null  object
 3   Name                      90015 non-null   object
 4   Age                       98110 non-null   float64
 5   SSN                       100000 non-null  object
 6   Occupation                100000 non-null  object
 7   Annual_Income             100000 non-null  float64
 8   Monthly_Inhand_Salary     84998 non-null   float64
 9   Num_Bank_Accounts         98693 non-null   float64
 10  Num_Credit_Card           97737 non-null   float64
 11  Interest_Rate             100000 non-null  int64
 12  Num_of_Loan               96124 non-null   float64
 13  Type_of_Loan              88592 non-null   object
 14  Delay_from_due_date       99409 non-null   float64
 15  Num_of_Delayed_Payment    92998 non-null   float64
 16  Changed_Credit_Limit      97909 non-null   float64
 17  Num_Credit_Inquiries      98035 non-null   float64
 18  Credit_Mix                100000 non-null  object
 19  Outstanding_Debt          100000 non-null  float64
 20  Credit_Utilization_Ratio  100000 non-null  float64
 21  Credit_History_Age        90970 non-null   object
 22  Payment_of_Min_Amount     100000 non-null  object
 23  Total_EMI_per_month       100000 non-null  float64
 24  Amount_invested_monthly   95521 non-null   float64
 25  Payment_Behaviour         100000 non-null  object
 26  Monthly_Balance           97123 non-null   float64
 27  Credit_Score              100000 non-null  object
 28  Before_payment            1786 non-null    float64
dtypes: float64(16), int64(1), object(12)
memory usage: 22.1+ MB

In [ ]:
df.isna().sum()

ID                              0
Customer_ID                     0
Month                           0
Name                         9985
Age                          1890
SSN                             0
Occupation                      0
Annual_Income                   0
Monthly_Inhand_Salary       15002
Num_Bank_Accounts            1307
Num_Credit_Card              2263
Interest_Rate                   0
Num_of_Loan                  3876
Type_of_Loan                11408
Delay_from_due_date           591
Num_of_Delayed_Payment       7002
Changed_Credit_Limit         2091
Num_Credit_Inquiries         1965
Credit_Mix                      0
Outstanding_Debt                0
Credit_Utilization_Ratio        0
Credit_History_Age           9030
Payment_of_Min_Amount           0
Total_EMI_per_month             0
Amount_invested_monthly      4479
Payment_Behaviour               0
Monthly_Balance              2877
Credit_Score                    0
Before_payment              98214
dtype: int64

In [ ]:
df

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,...,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score,Before_payment
0,0x1602,CUS_0xd40,January,Aaron Maashoh,23.0,821-00-0265,Scientist,19114.12,1824.843333,3.0,...,809.98,26.822620,22 Years and 1 Months,No,49.574949,80.415295,High_spent_Small_value_payments,312.494089,Good,NaN
1,0x1603,CUS_0xd40,February,Aaron Maashoh,23.0,821-00-0265,Scientist,19114.12,NaN,3.0,...,809.98,31.944960,NaN,No,49.574949,118.280222,Low_spent_Large_value_payments,284.629162,Good,1.0
2,0x1604,CUS_0xd40,March,Aaron Maashoh,50.0,821-00-0265,Scientist,19114.12,NaN,3.0,...,809.98,28.609352,22 Years and 3 Months,No,49.574949,81.699521,Low_spent_Medium_value_payments,331.209863,Good,NaN
3,0x1605,CUS_0xd40,April,Aaron Maashoh,23.0,821-00-0265,Scientist,19114.12,NaN,3.0,...,809.98,31.377862,22 Years and 4 Months,No,49.574949,199.458074,Low_spent_Small_value_payments,223.451310,Good,NaN
4,0x1606,CUS_0xd40,May,Aaron Maashoh,23.0,821-00-0265,Scientist,19114.12,1824.843333,3.0,...,809.98,24.797347,22 Years and 5 Months,No,49.574949,41.420153,High_spent_Medium_value_payments,341.489231,Good,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,0x25fe9,CUS_0x942c,April,Nicks,25.0,078-73-5990,Mechanic,39628.99,3359.415833,4.0,...,502.38,34.663572,31 Years and 6 Months,No,35.104023,60.971333,High_spent_Large_value_payments,NaN,Poor,NaN
99996,0x25fea,CUS_0x942c,May,Nicks,25.0,078-73-5990,Mechanic,39628.99,3359.415833,4.0,...,502.38,40.565631,31 Years and 7 Months,No,35.104023,54.185950,High_spent_Medium_value_payments,NaN,Poor,NaN
99997,0x25feb,CUS_0x942c,June,Nicks,25.0,078-73-5990,Mechanic,39628.99,3359.415833,4.0,...,502.38,41.255522,31 Years and 8 Months,No,35.104023,24.028477,High_spent_Large_value_payments,NaN,Poor,NaN
99998,0x25fec,CUS_0x942c,July,Nicks,25.0,078-73-5990,Mechanic,39628.99,3359.415833,4.0,...,502.38,33.638208,31 Years and 9 Months,No,35.104023,251.672582,Low_spent_Large_value_payments,NaN,Standard,NaN
99999,0x25fed,CUS_0x942c,August,Nicks,25.0,078-73-5990,Mechanic,39628.99,3359.415833,4.0,...,502.38,34.192463,31 Years and 10 Months,No,35.104023,167.163865,!@9#%8,NaN,Poor,NaN

In [ ]:
df.drop(['ID', 'Customer_ID', 'Name', 'SSN', 'Type_of_Loan', 'Credit_History_Age'], axis=1, inplace=True)

In [ ]:
df

,Month,Age,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Delay_from_due_date,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score,Before_payment
0,January,23.0,Scientist,19114.12,1824.843333,3.0,4.0,3,4.0,3.0,...,_,809.98,26.822620,No,49.574949,80.415295,High_spent_Small_value_payments,312.494089,Good,NaN
1,February,23.0,Scientist,19114.12,NaN,3.0,4.0,3,4.0,NaN,...,Good,809.98,31.944960,No,49.574949,118.280222,Low_spent_Large_value_payments,284.629162,Good,1.0
2,March,50.0,Scientist,19114.12,NaN,3.0,4.0,3,4.0,3.0,...,Good,809.98,28.609352,No,49.574949,81.699521,Low_spent_Medium_value_payments,331.209863,Good,NaN
3,April,23.0,Scientist,19114.12,NaN,3.0,4.0,3,4.0,5.0,...,Good,809.98,31.377862,No,49.574949,199.458074,Low_spent_Small_value_payments,223.451310,Good,NaN
4,May,23.0,Scientist,19114.12,1824.843333,3.0,4.0,3,4.0,6.0,...,Good,809.98,24.797347,No,49.574949,41.420153,High_spent_Medium_value_payments,341.489231,Good,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,April,25.0,Mechanic,39628.99,3359.415833,4.0,6.0,7,2.0,23.0,...,_,502.38,34.663572,No,35.104023,60.971333,High_spent_Large_value_payments,NaN,Poor,NaN
99996,May,25.0,Mechanic,39628.99,3359.415833,4.0,6.0,7,2.0,18.0,...,_,502.38,40.565631,No,35.104023,54.185950,High_spent_Medium_value_payments,NaN,Poor,NaN
99997,June,25.0,Mechanic,39628.99,3359.415833,4.0,6.0,5729,2.0,27.0,...,Good,502.38,41.255522,No,35.104023,24.028477,High_spent_Large_value_payments,NaN,Poor,NaN
99998,July,25.0,Mechanic,39628.99,3359.415833,4.0,6.0,7,2.0,20.0,...,Good,502.38,33.638208,No,35.104023,251.672582,Low_spent_Large_value_payments,NaN,Standard,NaN
99999,August,25.0,Mechanic,39628.99,3359.415833,4.0,6.0,7,2.0,18.0,...,Good,502.38,34.192463,No,35.104023,167.163865,!@9#%8,NaN,Poor,NaN

In [ ]:
if df.Credit_Score.isna().sum()>0:
  df.dropna(subset='Credit_Score')

In [ ]:
X=df.drop(['Credit_Score'], axis=1)
y=df['Credit_Score'].copy()

In [ ]:
X

,Month,Age,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Delay_from_due_date,...,Num_Credit_Inquiries,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Before_payment
0,January,23.0,Scientist,19114.12,1824.843333,3.0,4.0,3,4.0,3.0,...,4.0,_,809.98,26.822620,No,49.574949,80.415295,High_spent_Small_value_payments,312.494089,NaN
1,February,23.0,Scientist,19114.12,NaN,3.0,4.0,3,4.0,NaN,...,4.0,Good,809.98,31.944960,No,49.574949,118.280222,Low_spent_Large_value_payments,284.629162,1.0
2,March,50.0,Scientist,19114.12,NaN,3.0,4.0,3,4.0,3.0,...,4.0,Good,809.98,28.609352,No,49.574949,81.699521,Low_spent_Medium_value_payments,331.209863,NaN
3,April,23.0,Scientist,19114.12,NaN,3.0,4.0,3,4.0,5.0,...,4.0,Good,809.98,31.377862,No,49.574949,199.458074,Low_spent_Small_value_payments,223.451310,NaN
4,May,23.0,Scientist,19114.12,1824.843333,3.0,4.0,3,4.0,6.0,...,4.0,Good,809.98,24.797347,No,49.574949,41.420153,High_spent_Medium_value_payments,341.489231,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,April,25.0,Mechanic,39628.99,3359.415833,4.0,6.0,7,2.0,23.0,...,3.0,_,502.38,34.663572,No,35.104023,60.971333,High_spent_Large_value_payments,NaN,NaN
99996,May,25.0,Mechanic,39628.99,3359.415833,4.0,6.0,7,2.0,18.0,...,3.0,_,502.38,40.565631,No,35.104023,54.185950,High_spent_Medium_value_payments,NaN,NaN
99997,June,25.0,Mechanic,39628.99,3359.415833,4.0,6.0,5729,2.0,27.0,...,3.0,Good,502.38,41.255522,No,35.104023,24.028477,High_spent_Large_value_payments,NaN,NaN
99998,July,25.0,Mechanic,39628.99,3359.415833,4.0,6.0,7,2.0,20.0,...,3.0,Good,502.38,33.638208,No,35.104023,251.672582,Low_spent_Large_value_payments,NaN,NaN
99999,August,25.0,Mechanic,39628.99,3359.415833,4.0,6.0,7,2.0,18.0,...,3.0,Good,502.38,34.192463,No,35.104023,167.163865,!@9#%8,NaN,NaN

In [ ]:
y

0            Good
1            Good
2            Good
3            Good
4            Good
           ...
99995        Poor
99996        Poor
99997        Poor
99998    Standard
99999        Poor
Name: Credit_Score, Length: 100000, dtype: object

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test= train_test_split(X,y, test_size=0.2)

In [ ]:
num_features =X_train.select_dtypes(include=[np.number]).columns
cat_features =X_train.select_dtypes(exclude=[np.number]).columns

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier

In [ ]:
num_pipeline= Pipeline([
    ('impute', SimpleImputer(strategy='median')),
    ('scale', StandardScaler())
])

cat_pipeline=Pipeline([
    ('impute', SimpleImputer(strategy='most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

transformer= ColumnTransformer([
    ('num', num_pipeline, num_features),
    ('cat', cat_pipeline, cat_features)
], remainder='passthrough')

estimator=RandomForestClassifier()

full_pipeline=Pipeline([
    ('preprocessing', transformer),
    ('estimator', estimator)
])

In [ ]:
full_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scale',
                                                                   StandardScaler())]),
                                                  Index(['Age', 'Annual_Income', 'Monthly_Inhand_Salary', 'Num_Bank_Accounts',
       'Num_Credit_Card', 'Interest_Rate', 'Num_of_Loan',
       'Delay_from_due_date', 'Num_of_Delayed_Paymen...
       'Total_EMI_per_month', 'Amount_invested_monthly', 'Monthly_Balance',
       'Before_payment'],
      dtype='object')),
                                                 ('cat',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  Index(['Month', 'Occupation', 'Credit_Mix', 'Payment_of_Min_Amount',
       'Payment_Behaviour'],
      dtype='object'))])),
                ('estimator', RandomForestClassifier())])

In [ ]:
print(f'Train score:{full_pipeline.score(X_train, y_train)}\nTest score: {full_pipeline.score(X_test, y_test)}')

Train score:1.0
Test score: 0.7756